### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by zyf0330** [bearyinnovative/hubot-bearychat#10]
[Tue Jan 24 2017 11:51:23 GMT+0800 (CST)] INFO Connect using RTM mode
TypeError: this.client.run is not a function
  at BearyChatAdapter.run (/home/zyf/seebot/node_modules/hubot-bearychat/src/bearychat.coffee:43:5, <js>:57:26)
  at Robot.run (/home/zyf/seebot/node_modules/hubot/src/robot.coffee:590:5, <js>:464:27)
  at Object.<anonymous> (/home/zyf/seebot/node_modules/hubot/bin/hubot:168:8, <js>:182:11)
  at Object.<anonymous> (/home/zyf/seebot/node_modules/hubot/bin/hubot:5:1, <js>:185:4)
  at Module._compile (module.js:409:26)
  at Object.exports.run (/home/zyf/seebot/node_modules/coffee-script/lib/coffee-script/coffee-script.js:103:25)
  at compileScript (/home/zyf/seebot/node_modules/coffee-script/lib/coffee-script/command.js:171:29)
  at /home/zyf/seebot/node_modules/coffee-script/lib/coffee-script/command.js:143:18
  at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)

**Comment by bcho** [comment]
hi 请问你安装的是哪个版本？另外能提供一下以下命令的执行结果吗：

`npm list`

`node -v`

我这边的 hubot-bearychat 版本是 `0.3.0` , node 版本是 `v7.4.0`

另外也可以加入 http://openapi.beary.chat/join 我们的官方开发 api / 机器人反馈团队，这样沟通反馈可能会快一点 =D

**Comment by zyf0330** [comment]
我用的是 hubot-bearychat 0.3.0，node 4.5.0
我加了

**Comment by bcho** [comment]
fixed via https://github.com/bearyinnovative/hubot-bearychat/commit/09a225bc1a58573c9aa4cdc8df578c27652fc28a
