### ISSUE TITLE
在 bearychat 中 hubot 无响应

### ISSUE THREAD

**Issue by wutz** [bearyinnovative/hubot-bearychat#16]
从昨天开始，出现 2 次在 bearychat 中 `@hubot help` 无响应

查看 `hubot` 日志出现：

```
[Wed Mar 15 2017 18:07:07 GMT+0800 (CST)] DEBUG Executing listener callback for Message 'hubot shellcmd am ic'
spawn!
[Wed Mar 15 2017 21:30:07 GMT+0800 (CST)] ERROR ReferenceError: EventClosed is not defined
  at RTMClient.onWebSocketClose (/oits/hubot/node_modules/hubot-bearychat/src/rtm_client.coffee:86:5, <js>:104:24)
  at emitTwo (events.js:100:13)
  at WebSocket.emit (events.js:185:7)
  at WebSocket.cleanupWebsocketResources (/oits/hubot/node_modules/ws/lib/WebSocket.js:950:8)
  at emitNone (events.js:85:20)
  at TLSSocket.emit (events.js:179:7)
  at endReadableNT (_stream_readable.js:913:12)
  at _combinedTickCallback (internal/process/next_tick.js:74:11)
  at process._tickCallback (internal/process/next_tick.js:98:9)

[Wed Mar 15 2017 21:30:09 GMT+0800 (CST)] ERROR Error: not opened
  at WebSocket.send (/oits/hubot/node_modules/ws/lib/WebSocket.js:219:16)
  at RTMClient.writeWebSocket (/oits/hubot/node_modules/hubot-bearychat/src/rtm_client.coffee:80:5, <js>:96:27)
  at RTMClient.rtmPing (/oits/hubot/node_modules/hubot-bearychat/src/rtm_client.coffee:73:5, <js>:87:19)
  at Timeout.wrapper [as _onTimeout] (timers.js:408:11)
  at tryOnTimeout (timers.js:224:11)
  at Timer.listOnTimeout (timers.js:198:5)
```

重新启动 `hubot` 服务后，在 `bearychat` 中 `@hubot help` 工作正常

> 当前使用的 `hubot` 版本为 `2.19.0`, `hubot-bearychat` 版本为 `0.3.1`

**Comment by yuanbohan** [comment]
收到, 可能是我们长连接服务的问题, 我们查一下原因

**Comment by bcho** [comment]
@wutaizeng 这里有两个问题，其中一个少了 `EventClosed` 常量的已经在 [0.4.1](https://www.npmjs.com/package/hubot-bearychat) 里面修复了，可以安装尝试。

另外一个是自动重连机制的优化，我们会在下个版本添加支持。感谢你的反馈。

**Comment by wutz** [comment]
@bcho 好的，多谢！
