### ISSUE TITLE
hubot 机器人无响应

### ISSUE THREAD

**Issue by wutz** [bearyinnovative/hubot-bearychat#27]
最近频繁出现 `@hubot ...` 无响应

尝试重启 `hubot` 后恢复正常

下面是重启 `hubot` 前最后的日志信息

```
[Wed May 10 2017 13:31:47 GMT+0800 (CST)] ERROR client closed
[Wed May 10 2017 13:31:47 GMT+0800 (CST)] ERROR Error: not opened
  at WebSocket.send (/oits/eva/node_modules/ws/lib/WebSocket.js:219:16)
  at RTMClient.writeWebSocket (/oits/eva/node_modules/hubot-bearychat/src/rtm_client.coffee:81:5, <js>:100:27)
  at RTMClient.rtmPing (/oits/eva/node_modules/hubot-bearychat/src/rtm_client.coffee:74:5, <js>:91:19)
  at Timeout.wrapper [as _onTimeout] (timers.js:408:11)
  at tryOnTimeout (timers.js:224:11)
  at Timer.listOnTimeout (timers.js:198:5)
```

**Comment by bcho** [comment]
这个问题和 #18 相关

**Comment by wutz** [comment]
@bcho 这个问题处理优先级能否提高，之前这个问题偶尔会出现，但是最近出现有点频繁

**Comment by bcho** [comment]
@wutaizeng 👌

**Comment by loddit** [comment]
@wutaizeng 我们更新了版本， 我们先保守的升级 PATCH 版本号，你本地可以先重新安装来更新：
```
npm remove hubot-bearychat
npm install hubot-bearychat
```

**Comment by wutz** [comment]
@loddit 非常感谢，我先升级，观察观察

**Comment by wutz** [comment]
我们部署了多套 hubot, 其中之前一套 hubot-bearychat 升级到 0.5.2. 昨天晚上断线的问题出现了，升级到 0.5.2 正常工作。所以可以关闭此问题了 @loddit

**Comment by bcho** [comment]
:+1:
